export function CostSensitivityTab() {
  return (
    <div className="space-y-6 max-w-2xl">
      <div className="card">
        <p className="text-sm font-semibold text-slate-600 mb-2">Cost Sensitivity Analysis</p>
        <p className="text-sm text-slate-500 mb-6">
          Cost sensitivity and calibration results are generated by the Python pipeline scripts:
        </p>
        <div className="space-y-3">
          {[
            {
              label: 'Monthly Capacity-Cost Optimisation (RL-3)',
              script: 'python -m src.rl.evaluate_rl3_monthly_capacity_cost',
              output: 'data/rl3_monthly_capacity_cost_results.csv',
            },
            {
              label: 'Export Monthly Recommendations',
              script: 'python -m src.reporting.export_rl3_monthly_recommendations',
              output: 'data/app_exports/rl3_monthly_recommendations_summary.csv',
            },
          ].map((s) => (
            <div key={s.label} className="p-4 bg-slate-50 rounded-xl border border-slate-200">
              <p className="text-sm font-semibold text-slate-700 mb-2">{s.label}</p>
              <p className="text-xs text-slate-500 mb-1">Run with:</p>
              <code className="text-xs bg-slate-100 px-3 py-1.5 rounded-lg block text-slate-700">{s.script}</code>
              <p className="text-xs text-slate-400 mt-2">Output: <code>{s.output}</code></p>
            </div>
          ))}
        </div>
      </div>

      <div className="p-5 bg-amber-50 rounded-xl border border-amber-200 text-sm text-amber-800">
        <strong>Why isn't this automatic?</strong> Sensitivity sweeps are computationally intensive
        and require manual parameter configuration. Once you run the scripts above, the results
        will be available in the <code>data/</code> folder for analysis.
      </div>
    </div>
  )
}
